name: Deploy docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: |
          git config --global user.email "carlosandre1572@example.com"
          git config --global user.name "carlos-dev"
          npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
